# Generated by Django 4.2.7 on 2026-02-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('premium', 'Premium'), ('public', 'Public'), ('basic', 'Basic'), ('unified', 'Unified')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proxies_found', models.IntegerField(default=0)),
                ('proxies_working', models.IntegerField(default=0)),
                ('sources_tried', models.IntegerField(default=0)),
                ('sources_successful', models.IntegerField(default=0)),
                ('validate_proxies', models.BooleanField(default=True)),
                ('timeout', models.IntegerField(default=10)),
                ('max_workers', models.IntegerField(default=30)),
                ('log_messages', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('proxy_type', models.CharField(choices=[('http', 'HTTP'), ('socks4', 'SOCKS4'), ('socks5', 'SOCKS5')], max_length=10)),
                ('tier', models.IntegerField(choices=[(1, 'Premium'), (2, 'Public'), (3, 'Basic')])),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('is_working', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, unique=True)),
                ('credentials', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Proxy Credentials',
            },
        ),
        migrations.CreateModel(
            name='ProxySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tier', models.IntegerField(choices=[(1, 'Premium'), (2, 'Public'), (3, 'Basic')])),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('total_fetched', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_url', models.URLField(default='http://httpbin.org/ip')),
                ('success', models.BooleanField()),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('response_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='proxies.proxy')),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
        migrations.AddField(
            model_name='proxy',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxies.proxysource'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['is_working', 'tier'], name='proxies_pro_is_work_20cdc9_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['country', 'proxy_type'], name='proxies_pro_country_a146d2_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['created_at'], name='proxies_pro_created_fd8aaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together={('ip', 'port', 'proxy_type')},
        ),
    ]
