# Generated by Django 4.2.7 on 2026-02-01 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Generated filename for the export', max_length=255)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('txt', 'TXT'), ('xml', 'XML'), ('yaml', 'YAML')], max_length=10)),
                ('filters_applied', models.JSONField(default=dict, help_text='Filters that were applied during export')),
                ('file_size', models.BigIntegerField(help_text='Size of the exported file in bytes')),
                ('record_count', models.IntegerField(help_text='Number of proxy records in the export')),
                ('file_path', models.CharField(help_text='Path to the exported file on disk', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this export file will be automatically deleted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='proxies_exp_user_id_8543d7_idx'), models.Index(fields=['expires_at'], name='proxies_exp_expires_940c13_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this export configuration', max_length=100)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('txt', 'TXT'), ('xml', 'XML'), ('yaml', 'YAML')], max_length=10)),
                ('fields', models.JSONField(default=list, help_text='List of proxy fields to include in export')),
                ('options', models.JSONField(default=dict, help_text='Format-specific options (delimiters, formatting, etc.)')),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default export configuration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
