# Generated by Django 4.2.7 on 2026-02-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_exporthistory_exportconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporthistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExportConfig',
        ),
        migrations.DeleteModel(
            name='ExportHistory',
        ),
    ]
